#include<stdio.h>
#include<string.h>
typedef struct food1
{
	char name[10];
	char tst[10];
	char clr[10];
	int wgt;
	int qun;
}food;
int food2(food *ptr1,food *ptr2,food *ptr3,food *ptr4,food *ptr5)
{
	printf("--------[1].food information-------\n");
	printf("name=%s\t%p\n",ptr1->name,&ptr1->name);
	printf("colour=%s\t%p\n",ptr1->clr,&ptr1->clr);
	printf("teast=%s\t%p\n",ptr1->tst,&ptr1->tst);
	printf("weight=%d\t%p\n",ptr1->wgt,&ptr1->wgt);
	printf("quantity=%d\t%p\n",ptr1->qun,&ptr1->qun);
	printf("--------[2].food information----------\n");
	printf("name=%s\t%p\n",ptr2->name,&ptr2->name);
        printf("colour=%s\t%p\n",ptr2->clr,&ptr2->clr);
        printf("teast=%s\t%p\n",ptr2->tst,&ptr2->tst);
        printf("weight=%d\t%p\n",ptr2->wgt,&ptr2->wgt);
        printf("quantity=%d\t%p\n",ptr2->qun,&ptr2->qun);
	printf("---------[3].food information--------\n");
	printf("name=%s\t%p\n",ptr3->name,&ptr3->name);
        printf("colour=%s\t%p\n",ptr3->clr,&ptr3->clr);
        printf("teast=%s\t%p\n",ptr3->tst,&ptr3->tst);
        printf("weight=%d\t%p\n",ptr3->wgt,&ptr3->wgt);
        printf("quantity=%d\t%p\n",ptr3->qun,&ptr3->qun);
	printf("--------[4].food information--------\n");
	printf("name=%s\t%p\n",ptr4->name,&ptr4->name);
        printf("colour=%s\t%p\n",ptr4->clr,&ptr4->clr);
        printf("teast=%s\t%p\n",ptr4->tst,&ptr4->tst);
        printf("weight=%d\t%p\n",ptr4->wgt,&ptr4->wgt);
        printf("quantity=%d\t%p\n",ptr4->qun,&ptr4->qun);
	printf("----------[5].food information--------\n");
	printf("name=%s\t%p\n",ptr5->name,&ptr5->name);
        printf("colour=%s\t%p\n",ptr5->clr,&ptr5->clr);
        printf("teast=%s\t%p\n",ptr5->tst,&ptr5->tst);
        printf("weight=%d\t%p\n",ptr5->wgt,&ptr5->wgt);
        printf("quantity=%d\t%p\n",ptr5->qun,&ptr5->qun);
}
int main()
{
	int i=0;
	food a,b,c,d,e,*aptr,*bptr,*cptr,*dptr,*eptr;
	aptr=&a;
	bptr=&b;
	cptr=&c;
	dptr=&d;
	eptr=&e;
	printf("enter food name=");
	scanf("%s",aptr->name);
	printf("enter colour=");
	scanf("%s",aptr->clr);
	printf("enter teast=");
	scanf("%s",aptr->tst);
	printf("enter weight=");
	scanf("%d",&aptr->wgt);
	printf("enter quant=");
	scanf("%d",&aptr->qun);
	printf("enter food name=");
        scanf("%s",bptr->name);
        printf("enter colour=");
        scanf("%s",bptr->clr);
        printf("enter teast=");
        scanf("%s",bptr->tst);
        printf("enter weight=");
        scanf("%d",&bptr->wgt);
        printf("enter quant=");
        scanf("%d",&bptr->qun);
	printf("enter food name=");
        scanf("%s",cptr->name);
        printf("enter colour=");
        scanf("%s",cptr->clr);
        printf("enter teast=");
        scanf("%s",cptr->tst);
        printf("enter weight=");
        scanf("%d",&cptr->wgt);
        printf("enter quant=");
        scanf("%d",&cptr->qun);
	printf("enter food name=");
        scanf("%s",dptr->name);
        printf("enter colour=");
        scanf("%s",dptr->clr);
        printf("enter teast=");
        scanf("%s",dptr->tst);
        printf("enter weight=");
        scanf("%d",&dptr->wgt);
        printf("enter quant=");
        scanf("%d",&dptr->qun);
	printf("enter food name=");
        scanf("%s",eptr->name);
        printf("enter colour=");
        scanf("%s",eptr->clr);
        printf("enter teast=");
        scanf("%s",eptr->tst);
        printf("enter weight=");
        scanf("%d",&eptr->wgt);
        printf("enter quant=");
        scanf("%d",&eptr->qun);
	//printf("aptr=%p\nbptr=%p\ncptr=%p\ndptr=%p\neptr=\n",&aptr,&bptr,&cptr,&dptr,&eptr);
	printf("-------food info-------");
	printf("name=%s\n",a.name);
	printf("colour=%s\n",a.clr);
	printf("tst=%s\n",a.tst);
	printf("weight=%d\n",a.wgt);
	printf("qunt=%d\n",a.qun);
	printf("name=%s\n",b.name);
        printf("colour=%s\n",b.clr);
        printf("tst=%s\n",b.tst);
        printf("weight=%d\n",b.wgt);
        printf("qunt=%d\n",b.qun);
	printf("name=%s\n",c.name);
        printf("colour=%s\n",c.clr);
        printf("tst=%s\n",c.tst);
        printf("weight=%d\n",c.wgt);
        printf("qunt=%d\n",c.qun);
	printf("name=%s\n",d.name);
        printf("colour=%s\n",d.clr);
        printf("tst=%s\n",d.tst);
        printf("weight=%d\n",d.wgt);
        printf("qunt=%d\n",d.qun);
	printf("name=%s\n",e.name);
        printf("colour=%s\n",e.clr);
        printf("tst=%s\n",e.tst);
        printf("weight=%d\n",e.wgt);
        printf("qunt=%d\n",e.qun);
	food2(aptr,bptr,cptr,dptr,eptr);
	return 0;
}

